# 矩陣分解

In [136]:
import numpy as np
import time

In [47]:
user = 5
item = 5
latent = 2 # K 隱語義

In [48]:
y = np.array([[1,1,1,0,0],
              [1,1,1,0,0], 
              [1,1,1,0,0],
              [0,0,0,1,1],
              [0,0,0,1,1]], dtype = np.float)

In [49]:
y_hat = y.copy()

In [50]:
y_hat[0,4] = y_hat[1,3] = y_hat[2,2] = y_hat[3,1] = y_hat[4,0] = None

In [51]:
y_hat

array([[ 1.,  1.,  1.,  0., nan],
       [ 1.,  1.,  1., nan,  0.],
       [ 1.,  1., nan,  0.,  0.],
       [ 0., nan,  0.,  1.,  1.],
       [nan,  0.,  0.,  1.,  1.]])

In [52]:
y_hat2 = np.nan_to_num(y_hat, nan = 0.5)

In [53]:
y_hat2

array([[1. , 1. , 1. , 0. , 0.5],
       [1. , 1. , 1. , 0.5, 0. ],
       [1. , 1. , 0.5, 0. , 0. ],
       [0. , 0.5, 0. , 1. , 1. ],
       [0.5, 0. , 0. , 1. , 1. ]])

In [54]:
U, S, Vh = np.linalg.svd(y_hat2, full_matrices=True)

In [21]:
U.shape

(5, 5)

In [23]:
S.shape

(5,)

In [24]:
Vh.shape

(5, 5)

In [25]:
S.shape

(5,)

In [26]:

S

array([3.03208889, 1.84729636, 0.5       , 0.5       , 0.37938524])

In [30]:
U[:,:latent]

array([[-0.56857902,  0.19746542],
       [-0.56857902,  0.19746542],
       [-0.44909879,  0.29312841],
       [-0.27545061, -0.64656421],
       [-0.27545061, -0.64656421]])

In [36]:
U[:,:latent] * np.sqrt(S[:latent]).reshape(1,-1)

array([[-0.99006064,  0.26838568],
       [-0.99006064,  0.26838568],
       [-0.78201097,  0.39840631],
       [-0.47963923, -0.87877956],
       [-0.47963923, -0.87877956]])

In [38]:
Vh[:latent, :] * np.sqrt(S[:latent]).reshape(-1,1)

array([[-0.99006064, -0.99006064, -0.78201097, -0.47963923, -0.47963923],
       [ 0.26838568,  0.26838568,  0.39840631, -0.87877956, -0.87877956]])

In [41]:
P = U[:,:latent] * np.sqrt(S[:latent]).reshape(1,-1)
Q = Vh[:latent, :] * np.sqrt(S[:latent]).reshape(-1,1)

In [43]:
P @ Q

array([[1.05225095, 1.05225095, 0.88116483, 0.23902007, 0.23902007],
       [1.05225095, 1.05225095, 0.88116483, 0.23902007, 0.23902007],
       [0.88116483, 0.88116483, 0.77026874, 0.02497182, 0.02497182],
       [0.23902007, 0.23902007, 0.02497182, 1.0023073 , 1.0023073 ],
       [0.23902007, 0.23902007, 0.02497182, 1.0023073 , 1.0023073 ]])

In [45]:
y

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.]])

In [ ]:
######################################

In [77]:
t1 = np.random.choice(range(1, 11), size = 35).reshape(7,5)

In [78]:
t1 = np.array(t1, dtype = np.float)

In [79]:
t1[0,0] = t1[2,1] = t1[6,1] = t1[4,3] = t1[2,3] =\
t1[1,3] = t1[3,2] = t1[0,4] = t1[2,4] = t1[4,0] = None 

In [80]:
t1

array([[nan,  2.,  4.,  8., nan],
       [ 4.,  2.,  1., nan,  8.],
       [ 3., nan,  6., nan, nan],
       [ 2.,  2., nan,  4.,  2.],
       [nan,  3.,  8., nan,  7.],
       [ 8.,  9.,  3.,  2., 10.],
       [ 6., nan,  5.,  3.,  7.]])

In [81]:
t2 = np.nan_to_num(t1, 0)

In [83]:
U, S, Vh = np.linalg.svd(t2, full_matrices=True)

In [84]:
print(U.shape)
print(S.shape)
print(Vh.shape)

(7, 7)
(5,)
(5, 5)


In [102]:
latent = 3

In [87]:
U[:,:latent]

array([[-0.1728582 , -0.76904163],
       [-0.36206718,  0.34292623],
       [-0.16304388, -0.31482176],
       [-0.16453089, -0.12751071],
       [-0.39529682, -0.21090506],
       [-0.66291144,  0.33629222],
       [-0.43550262, -0.13428122]])

In [89]:
Vh[:latent,:]

array([[-0.44155216, -0.37079452, -0.40589138, -0.20264767, -0.6795066 ],
       [ 0.21190722,  0.13255736, -0.61525434, -0.65859603,  0.35388876]])

In [103]:
U[:,:latent] * np.sqrt(S[:latent]).reshape(1,-1)

array([[-0.83010293, -2.39596382, -1.18639622],
       [-1.73872581,  1.0683932 ,  0.07673955],
       [-0.78297238, -0.98083316,  1.13264776],
       [-0.79011336, -0.39726204, -1.1993048 ],
       [-1.89830183, -0.65707874,  1.72114149],
       [-3.18344581,  1.0477248 , -0.9677638 ],
       [-2.09137888, -0.4183557 ,  0.34701237]])

In [104]:
Vh[:latent, :] * np.sqrt(S[:latent]).reshape(-1,1)

array([[-2.12043009, -1.78063646, -1.94917922, -0.97315847, -3.26313942],
       [ 0.66020096,  0.41298498, -1.91683658, -2.05186844,  1.10254715],
       [-0.5339423 , -1.00127697,  1.80623196, -1.86202519,  0.36972781]])

In [105]:
tP = U[:,:latent] * np.sqrt(S[:latent]).reshape(1,-1)
tQ = Vh[:latent, :] * np.sqrt(S[:latent]).reshape(-1,1)

In [108]:
np.around(tP @ tQ,1)

array([[ 0.8,  1.7,  4.1,  7.9, -0.4],
       [ 4.4,  3.5,  1.5, -0.6,  6.9],
       [ 0.4, -0.1,  5.5,  0.7,  1.9],
       [ 2.1,  2.4,  0.1,  3.8,  1.7],
       [ 2.7,  1.4,  8.1, -0. ,  6.1],
       [ 8. ,  7.1,  2.4,  2.8, 11.2],
       [ 4. ,  3.2,  5.5,  2.2,  6.5]])

In [100]:
t1

array([[ 0.,  2.,  4.,  8.,  0.],
       [ 4.,  2.,  1.,  0.,  8.],
       [ 3.,  0.,  6.,  0.,  0.],
       [ 2.,  2.,  0.,  4.,  2.],
       [ 0.,  3.,  8.,  0.,  7.],
       [ 8.,  9.,  3.,  2., 10.],
       [ 6.,  0.,  5.,  3.,  7.]])

推荐算法之--矩阵分解(Matrix Factorization)
https://blog.csdn.net/qq_36870202/article/details/123390202?spm=1001.2101.3001.6661.1&utm_medium=distribute.pc_relevant_t0.none-task-blog-2%7Edefault%7ECTRLIST%7Edefault-1-123390202-blog-84525643.pc_relevant_sortByAnswer&depth_1-utm_source=distribute.pc_relevant_t0.none-task-blog-2%7Edefault%7ECTRLIST%7Edefault-1-123390202-blog-84525643.pc_relevant_sortByAnswer&utm_relevant_index=1

<href>https://blog.csdn.net/qq_36870202/article/details/123390202?spm=1001.2101.3001.6661.1&utm_medium=distribute.pc_relevant_t0.none-task-blog-2%7Edefault%7ECTRLIST%7Edefault-1-123390202-blog-84525643.pc_relevant_sortByAnswer&depth_1-utm_source=distribute.pc_relevant_t0.none-task-blog-2%7Edefault%7ECTRLIST%7Edefault-1-123390202-blog-84525643.pc_relevant_sortByAnswer&utm_relevant_index=1 <href/>

In [110]:
from math import pow
import numpy

In [115]:
def matrix_factorzation(R, P, Q, K, N = 5000, step = 0.0002, beta = 0.02):
    # N 是迭代次數，step為學習率，beta是正則化參數
    Q = Q.T # 矩陣轉置
    for n in range(N):
        for m in range(len(R)):
            for n in range(len(R[m])):
                if R[m][n] > 0: # 對原始矩陣中有評分的項目計算lossfunc
                    emn = R[m][n] - np.dot(P[m, :], Q[:,n]) #.dot(P,Q)表示矩陣乘法
                    for k in range(K):
                        P[m][k] = P[m][k] + step*(2*emn*Q[k][n] - beta * P[m][k])
                        Q[k][n] = Q[k][n] + step*(2*emn*P[m][k] - beta * Q[k][n])
        e = 0
        for m in range(len(R)):
            for n in range(len(R[m])):
                if R[m][n] > 0:
                    e = e+pow(R[m][n] - np.dot(P[m,:], Q[:,n]),2)
                    for k in range(K):
                        e = e+(beta/2) * (pow(P[m][k],2) + pow(Q[k][n],2))
        if e < 0.001:
            break
    return P, Q.T
            

In [116]:
R = [[5,3,0,1],
     [4,0,0,1],
     [1,1,0,5],
     [0,1,5,4]]

In [131]:
R = np.array(R)
K = 10
P = np.random.rand(len(R), K)
Q = np.random.rand(len(R[0]), K)


In [137]:
%%time
p, q = matrix_factorzation(R, P, Q, K)

Wall time: 4.08 s


In [133]:
np.dot(p,q.T)

array([[4.98098836, 2.98117395, 3.34226551, 1.00297659],
       [3.98434392, 1.40927965, 2.68520117, 1.00157301],
       [1.00271252, 0.99421379, 4.18474791, 4.97073336],
       [3.45080484, 1.00630655, 4.98560325, 3.98868165]])

In [134]:
p @ q.T

array([[4.98098836, 2.98117395, 3.34226551, 1.00297659],
       [3.98434392, 1.40927965, 2.68520117, 1.00157301],
       [1.00271252, 0.99421379, 4.18474791, 4.97073336],
       [3.45080484, 1.00630655, 4.98560325, 3.98868165]])

In [135]:
R

array([[5, 3, 0, 1],
       [4, 0, 0, 1],
       [1, 1, 0, 5],
       [0, 1, 5, 4]])